# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-feed

whitelist:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-feed

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
debugMode                : false
host                     : 0.0.0.0
collections_dir          : "collections"
locale                   : "en-GB"
title                    : "Keep-Alive I.T"
title_separator          : "|"
subtitle                 : "I.T Development & Operations Consultancy Solutions for Businesses and Consumers"
name                     : "Keep-Alive I.T Ltd." # &name is a YAML anchor which can be *referenced later
description              : &description "We're a Modern, UK based, Hardware & Software I.T Consultancy Company who provides Agile I.T Development & Operations (DevOps) Solutions for Businesses, Consumers, and Non-Profit Organisations."
url                      : https://staging.keepaliveit.co.uk # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/images/logo.png" # path of logo image to display in header
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "false" # false (default), "disqus", "discourse", "facebook", "staticman_v2", "staticman", "utterances", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : # "master"
  commitMessage          : # "New comment by {fields.name}"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "_data/comments/{options.slug}"
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
  endpoint               : # URL of your own deployment with trailing slash, will fallback to the public instance
reCaptcha:
  siteKey                : # "6LdRBykTAAAAAFB46MnIu6ixuxwu9W1ihFF8G60Q"
  secret                 : # "PznnZGu3P6eTHRPLORniSq+J61YEf+A9zmColXDM5icqF49gbunH51B8+h+i2IvewpuxtA9TFoK68TuhUp/X3YKmmqhXasegHYabY50fqF9nJh9npWNhvITdkQHeaOqnFXUIwxfiEeUt49Yoa2waRR7a5LdRAP3SVM8hz0KIBT4="

company_number: 12358813
chat_widget: false
facebook_pixel: false

atom_feed:
  path                   : # blank (default) uses feed.xml

search                   : false # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : algolia # lunr (default), algolia
algolia:
  application_id         : RBGT19CYLC # YOUR_APPLICATION_ID
  index_name             : site # YOUR_INDEX_NAME
  search_only_api_key    : 737f32bd6dbcbcbae888cb69cf9e637b # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : false # true (default), false
  files_to_exclude:
    - _posts/2017-11-28-post-exclude-search.md

# SEO Related
google_site_verification : "UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y" # Replace this with your ID, or delete
bing_site_verification   : "1D30BBB9A9F1B4770FECEB47FFF5F1D5"
yandex_site_verification : "407dd707603a546b"
naver_site_verification  :

# Social Sharing
twitter:
  username               : &twitter "keepaliveit"
facebook:
  username               : &facebook "keepaliveitservices"
  app_id                 :
  publisher              :
og_image                 : "/assets/images/site-logo.png" # Open Graph/Twitter default site image
# For specifying social profiles, used in _includes/seo.html
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Organization # Person or Organization (defaults to Person)
  name                   : Keep-Alive I.T Ltd. # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/keepaliveit"
    - "https://www.facebook.com/keepaliveitltd/"

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-153604700-1" # Replace this with your ID, or delete
    anonymize_ip         : true


# Site Author
author:
  name             : "Joel Murphy" # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/joel-murphy.jpg"
  bio              : "Joel is a Lead Consultant at Keep-Alive I.T Services and works with clients to deliver I.T strategies, technical roadmaps, and functional I.T implementations. He also writes technical articles for the Keep-Alive I.T Services website whenever he's not tied up with learning new technologies himself."
  location         : "Wales, UK"
  links:
    - label: "joel-murphy.co.uk"
      icon: "fas fa-fw fa-link"
      url: "https://joel-murphy.co.uk"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jjmpsp"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mmistakes"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/keepaliveit"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KeepAliveIT/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/keepaliveitltd"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/keepaliveitltd/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "http://linkedin.com/company/keepaliveit"


# Reading Files
include:
  - .htaccess
  - _pages
  - .nojekyll
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .idea
  - .jekyll-assets-cache
  - .sass-cache
  - scripts
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - assets/gulp-config
  - assets/styles
  - _industry
  - csv_to_md.py
  - data.csv
  - hologram_config.yml
  - webpack.config.js
keep_files:
  - .git
  - .svn
  - assets
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  testimonial:
    output: false
    permalink: /testimonial/:path/
  industry:
    output: true
    permalink: /it-consultations-for/:path/
  consultation:
    output: true
    permalink: /it-consultation/:path/
  techtip:
    output: true
    permalink: /tech-tips/:path/
  jobs:
    output: true
    permalink: /jobs/:path/
  benefit:
    output: true
    permalink: /benefits-of-effective-it/:path/
  solutions:
    output: true
    permalink: /:collection/:path/
  services:
    output: true
    permalink: /:collection/:path/
  resources:
    output: true
    permalink: /:collection/:path/
  docs:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  cloud-products-and-services:
    output: true
    permalink: /:collection/:path/
  cloud-products-and-services-for-smes:
    output: true
    permalink: /:collection/:path/
  cloud-products-and-services-for-startups:
    output: true
    permalink: /:collection/:path/
  cloud-products-and-services-for-non-profit-organisations:
    output: true
    permalink: /:collection/:path/
  cloud-products-and-services-for-public-sector-organisations:
    output: true
    permalink: /:collection/:path/
  cloud-products-and-services-for-consumers:
    output: true
    permalink: /:collection/:path/
  office-fitting-services:
    output: true
    permalink: /:collection/:path/
  office-fitting-services-for-smes:
    output: true
    permalink: /:collection/:path/
  office-fitting-services-for-startups:
    output: true
    permalink: /:collection/:path/
  office-fitting-services-for-public-sector-organisations:
    output: true
    permalink: /:collection/:path/
  it-consultancy-services:
    output: true
    permalink: /:collection/:path/
  it-consultancy-services-for-smes:
    output: true
    permalink: /:collection/:path/
  it-consultancy-services-for-startups:
    output: true
    permalink: /:collection/:path/
  it-consultancy-services-for-non-profit-organisations:
    output: true
    permalink: /:collection/:path/
  it-consultancy-services-for-public-sector-organisations:
    output: true
    permalink: /:collection/:path/
  website-products-and-services:
    output: true
    permalink: /:collection/:path/
  website-products-and-services-for-consumers:
    output: true
    permalink: /:collection/:path/
  website-products-and-services-for-smes:
    output: true
    permalink: /:collection/:path/
  website-products-and-services-for-startups:
    output: true
    permalink: /:collection/:path/
  website-products-and-services-for-public-sector-organisations:
    output: true
    permalink: /:collection/:path/
  it-hardware-products-and-services:
    output: true
    permalink: /:collection/:path/
  it-hardware-products-and-services-for-smes:
    output: true
    permalink: /:collection/:path/
  it-hardware-products-and-services-for-consumers:
    output: true
    permalink: /:collection/:path/
  it-hardware-products-and-services-for-startups:
    output: true
    permalink: /:collection/:path/
  it-hardware-products-and-services-for-public-sector-organisations:
    output: true
    permalink: /:collection/:path/
  software-products-and-services:
    output: true
    permalink: /:collection/:path/
  software-products-and-services-for-smes:
    output: true
    permalink: /:collection/:path/
  software-products-and-services-for-startups:
    output: true
    permalink: /:collection/:path/
  software-products-and-services-for-consumers:
    output: true
    permalink: /:collection/:path/
  software-products-and-services-for-public-sector-organisations:
    output: true
    permalink: /:collection/:path/
  it-tools-and-utilities:
    output: true
    permalink: /:collection/:path/
  recruitment:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true


# Sass options
sass:
  sass_dir: assets/css
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/London # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Pagination:
############################################################

pagination:
  # Site-wide kill switch, if disabled here then it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 4

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/


autopages:
  # Site-wide kill switch, disable here and it doesn't run at all
  enabled: true

  # Category pages, omit entire config element to disable
  categories:
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts:
      - 'autopage_category.html'
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
    title: 'Posts in category :cat'
    # Optional, the permalink for the  pagination page (:cat is replaced),
    # the pagination permalink path is then appended to this permalink structure
    permalink: '/categories/:cat'

  # Collection pages, omit to disable
  collections:
    layouts:
      - 'autopage_collection.html'
    title: 'Posts in collection :coll' # :coll is replaced by the collection name
    permalink: '/collections/:coll'

  # Tag pages, omit to disable
  tags:
    layouts:
      - 'autopage_tags.html'
    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
    permalink: '/tags/:tag'


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
