version: "3"
services:
  website:
    #image: keepaliveit/jekyll-gulp-docker:latest
    #command: jekyll serve --config _config.yml,_config.test.yml,_config.dev.yml -H 0.0.0.0 --force_polling --incremental
    #command: npm serve
    #restart: on-failure
    build:
      context: ./
      dockerfile: ./jekyll-gulp-docker/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
      - /srv/jekyll/node_modules